<a href="https://colab.research.google.com/github/CaldeCrack/CC3001-Algoritmos-y-Estructuras-de-Datos/blob/main/Tareas/Tarea_3_ProgramacionDinamica_AndresCalderon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CC3001 2022-2 - Tarea 3: Programación Dinámica -- Andrés Calderón Guardia


## Profesores: Nelson Baloian, Jérémy Barbay, Benjamín Bustos, Patricio Poblete

Según las condiciones de su sección, pueden entregar un link a su tarea en `colab` o subir un archivo en el formato Jupyter NoteBook (`.ipynb`). Puede crear todas las funciones auxiliares que requiera para implementar las funciones solicitadas. Para programar las funciones debe usar los *array* de *numpy*. Los únicos métodos de los objetos de tipo *array* que puede utilizar en su solución son los siguientes:

- El método *array* para crear un arreglo.
- Los métodos *zeros*, *ones* y *full* para inicializar un *array*.

No se puede utilizar ningún otro método disponible en módulos de Python.

# El Problema

Suponga que se tienen dos series de valores $A$ y $B$, representadas como arreglos, Por ejemplo:


In [ ]:
import math
import numpy

A = numpy.array([1, 1, 3, 5, 2])
B = numpy.array([1, 2, 2, 5, 1])

El problema a resolver es medir cuánto se parecen las series de valores. Si las series tienen el mismo largo, como en el ejemplo, una forma de medir su parecido es calculando la distancia Euclidiana entre ambas series:

In [ ]:
def distanciaEuclidiana(serie1, serie2):
    assert len(serie1) == len(serie2)
    resultado = 0
    for i in range(len(serie1)):
        resultado += (serie1[i] - serie2[i]) ** 2
    return math.sqrt(resultado)

print(distanciaEuclidiana(A, B))

1.7320508075688772


En el caso que el largo de las series de valores no sean iguales, no es posible calcular la distancia Euclidiana. Para resolver esto, se propone la siguiente fórmula recursiva para calcular la distancia entre las dos series de valores:

- Sea una serie de valores $A$ de largo $i$ (denominada $A_i$) y una serie de valores $B$ de largo $j$ (denominada $B_j$).
- Si las dos series de valores tienen largo cero, su distancia es 0.
- Si una de las series de valores tiene largo 0, y la otra tiene largo estrictamente mayor que cero, su distancia es "infinito" (esto se puede representar con el valor *numpy.inf*)
- Si no, la distancia entre las series $A_i$ y $B_j$ se define recursivamente como:

$$ distancia(A_i, B_j) = costo(A_i, B_j) + \min\{ distancia(A_{i-1}, B_{j}),  distancia(A_{i}, B_{j-1}), distancia(A_{i-1}, B_{j-1})\} $$

La función $costo(A_i, B_j)$ devuelve un número que corresponde al cuadrado de la diferencia entre el $i$-ésimo valor de la serie $A$ y el $j$-ésimo valor de la serie $B$. *Nota*: Usted no debe editar la función de costo.

In [ ]:
# costo: num num -> num
def costo(x, y):
    return (x - y) ** 2

# Parte 1

Implemente usando recursión el cálculo de la distancia entre dos series de valores.

In [ ]:
# Solución

import numpy

def distanciaRecursiva(A, B):
    # Casos particulares
    if len(A) + len(B) == 0: # Ambos arrays tienen largo 0
      return 0
    elif len(A) == 0 or len(B) == 0: # Un array tiene largo 0 y el otro mayor estricto a 0
      return numpy.inf

    # Acciones a ejecutar en cada iteración
    if len(A) <= 1: # Reducir array A a largo 0
      Aminus = []
    else: # Reducir largo del array A en uno
      Aminus = A[:-1]
    if len(B) <= 1: # Reducir array B a largo 0
      Bminus = []
    else: # Reducir largo del array B en uno
      Bminus = B[:-1]

    # Cálculo de la distancia
    return costo(A[-1], B[-1]) + min(distanciaRecursiva(Aminus, B), distanciaRecursiva(A, Bminus), distanciaRecursiva(Aminus, Bminus))

# Algunos tests que le pueden servir para probar su codigo
A = numpy.array([1, 1, 2, 3, 2, 0])
B = numpy.array([0, 1, 1, 2, 3, 2, 1])
assert distanciaRecursiva(A, B) == 2
A = numpy.array([1, 2, 3, 3, 4, 1])
B = numpy.array([1, 1, 3, 4, 3, 1])
assert distanciaRecursiva(A, B) == 2
A = numpy.array([3, 1, 2, 2, 1])
B = numpy.array([2, 0, 0, 3, 3, 1, 0])
assert distanciaRecursiva(A, B) == 6
A = numpy.array([1, 4, 5, 10, 9, 3, 2, 6, 8, 4])
B = numpy.array([1, 7, 3, 4, 1, 10, 5, 4, 7, 4])
assert distanciaRecursiva(A, B) == 37
print('Su codigo paso todos los tests!')

Su codigo paso todos los tests!


# Parte 2

Implemente usando la técnica de memoización el cálculo de la distancia entre dos series de valores, de forma de evitar que se repitan llamados recursivos. Puede usar como base su código implementado para la Parte 1.

In [ ]:
# Solución

import numpy

def distanciaMemoizacion(A, B):
    d = numpy.zeros((len(A) + 1, len(B) + 1)) # Matriz con todas las comparaciones posibles

    # Función auxiliar
    def calcDistancia(A, B):
      # Acciones a ejecutar en cada iteración
      if len(A) <= 1: # Reducir array A a largo 0
        Aminus = []
      else: # Reducir largo del array A en uno
        Aminus = A[:-1]
      if len(B) <= 1: # Reducir array B a largo 0
        Bminus = []
      else: # Reducir largo del array B en uno
        Bminus = B[:-1]

      # Cálculo de la distancia
      if len(A) + len(B) > 0 and d[len(A), len(B)] == 0: # Asignar valor a celda sin calcular
        if len(A) == 0 or len(B) == 0: # Caso particular
          d[len(A), len(B)] = numpy.inf
        else: # Almacenar los distintos valores
          d[len(A), len(B)] = costo(A[-1], B[-1]) + min(calcDistancia(Aminus, B), calcDistancia(A, Bminus), calcDistancia(Aminus, Bminus))
      return d[len(A), len(B)]
    return int(calcDistancia(A, B))

# Algunos tests que le pueden servir para probar su codigo
A = numpy.array([1, 1, 2, 3, 2, 0])
B = numpy.array([0, 1, 1, 2, 3, 2, 1])
assert distanciaMemoizacion(A, B) == 2
A = numpy.array([1, 2, 3, 3, 4, 1])
B = numpy.array([1, 1, 3, 4, 3, 1])
assert distanciaMemoizacion(A, B) == 2
A = numpy.array([3, 1, 2, 2, 1])
B = numpy.array([2, 0, 0, 3, 3, 1, 0])
assert distanciaMemoizacion(A, B) == 6
A = numpy.array([1, 4, 5, 10, 9, 3, 2, 6, 8, 4])
B = numpy.array([1, 7, 3, 4, 1, 10, 5, 4, 7, 4])
assert distanciaMemoizacion(A, B) == 37
print('Su codigo paso todos los tests!')

Su codigo paso todos los tests!


# Parte 3

Implemente utilizando tabulación (Programación Dinámica) el cálculo de la distancia entre dos series de valores. Para esto, defina una matriz $C$ en donde vaya guardando los resultados a los subproblemas. *Sugerencia*: Inicialice la primera fila y la primera columna de la matriz $C$, y luego piense en cómo ir rellenando el resto de la matriz con los valores previamente calculados.

In [ ]:
# Solución

import numpy

def distanciaProgramacionDinamica(A, B):
    C = numpy.zeros((len(A) + 1, len(B) + 1)) # Matriz con todas las posibles comparaciones

    # Inicialización de la primera fila y columna de la matriz C
    for i in range(1, len(A) + 1): # Primera fila de C
      C[i, 0] = numpy.inf
    for j in range(1, len(B) + 1): # Primera columna de C
      C[0, j] = numpy.inf

    # Tabulación de la matriz
    for i in range(1, len(A) + 1): # Completación de los valores por columna
      for j in range(1, len(B) + 1): # Completación de los valores por fila
        C[i, j] = costo(A[i - 1], B[j - 1]) + min(C[i - 1, j], C[i, j - 1], C[i - 1, j - 1]) # Asignación de los valores
    return int(C[len(A), len(B)])

# Algunos tests que le pueden servir para probar su codigo
A = numpy.array([1, 1, 2, 3, 2, 0])
B = numpy.array([0, 1, 1, 2, 3, 2, 1])
assert distanciaProgramacionDinamica(A, B) == 2
A = numpy.array([1, 2, 3, 3, 4, 1])
B = numpy.array([1, 1, 3, 4, 3, 1])
assert distanciaProgramacionDinamica(A, B) == 2
A = numpy.array([3, 1, 2, 2, 1])
B = numpy.array([2, 0, 0, 3, 3, 1, 0])
assert distanciaProgramacionDinamica(A, B) == 6
A = numpy.array([1,4,5,10,9,3,2,6,8,4])
B = numpy.array([1,7,3,4,1,10,5,4,7,4])
assert distanciaProgramacionDinamica(A, B) == 37
A = numpy.array([1,4,5,10,9,3,2,6,8,4,1,4,5,10,9,3,2,6,8,4])
B = numpy.array([1,7,3,4,1,10,5,4,7,4,1,7,3,4,1,10,5,4,7,4])
assert distanciaProgramacionDinamica(A, B) == 74
print('Su codigo paso todos los tests!')

Su codigo paso todos los tests!


# Parte 4

Pruebe cuánto tiempo demora cada una de las funciones implementados en calcular la distancia para series de valores. Para esto, el siguiente código mide el tiempo que demoran las tres funciones con series de valores $A$ y $B$ del mismo largo, con largo $n$ variando desde 1 hasta 10. Concluya sobre la eficiencia de las funciones implementadas a partir de los resultados obtenidos.

In [ ]:
for n in range(1,11):
    A = numpy.random.randint(1,10,n)
    B = numpy.random.randint(1,10,n)
    print(A, B)
    %timeit distanciaRecursiva(A,B)
    %timeit distanciaMemoizacion(A,B)
    %timeit distanciaProgramacionDinamica(A,B)

[3] [4]
2.84 µs ± 55.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
11.8 µs ± 153 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
7.74 µs ± 140 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[9 4] [9 6]
22.5 µs ± 320 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
55.3 µs ± 2.53 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
22 µs ± 514 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[7 3 9] [5 6 5]
120 µs ± 939 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
85.3 µs ± 390 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
45.5 µs ± 1.29 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[7 5 3 8] [7 2 7 9]
631 µs ± 5.98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
166 µs ± 2.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
77.8 µs ± 2.84 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[7 7 1 2 1] [8 9 4 3 3]
3.4 ms ± 94.2 µs per loop (mean ± std. de

# Conclusión sobre los resultados experimentales:

El primer algoritmo solo resulta ser más eficiente por sobre los otros 2 para series de datos pequeñas, en particular hasta $n$ igual a 2 (aunque el tercer algoritmo supera a este para $n$ igual a 2 pero el segundo es más lento respecto a este), mientras que a medida que crece el valor de $n$ lo que se demora este algoritmo crece mucho más que los otros dos. Para el segundo algoritmo en su generalidad sus tiempos suelen estar entre ambos pero mucho más cerca del tercer algoritmo que resulta ser el más eficiente de los tres para valores grandes de $n$, siendo este último aproximadamente el doble de rápido que el anterior.